### ISSUE TITLE
Passwordless and google log in are not working in mozillians staging

### ISSUE THREAD

**Issue by rleitan** [mozilla-iam/auth0-deploy#223]
[STR]:
1.Go to https://web-mozillians-staging.production.paas.mozilla.community/en-US/
2.Log in with a passwordless account
3.Open the link received via the email

[Expected result]:
Log in should be successful

[Actual result]:
Error page is displayed
![2018-10-04_11h30_31](https://user-images.githubusercontent.com/41474886/46462225-83e55980-c7c9-11e8-8c73-6c527fc92218.png)

**Comment by gdestuynder** [comment]
This RP is set with AAI medium which requires 2FA but passwordless does not support 2FA.
I'm going to add more RPs with the different AAI levels that we use (LOW and MEDIUM)
- LOW means no specific requirements
- MEDIUM means 2FA or HIGH ASSURANCE IDP (i.e. Google) right now

**Comment by gdestuynder** [comment]
Note I found that this would fail for Google accounts as the HIGH ASSURANCE IDP was set in our mapping but not in the fallback defaults. Our mapping is not yet available online so it always fallbacks to default..
There are some docs about the whole thing here: https://github.com/mozilla-iam/cis/blob/profilev2/docs/AuthenticatorAssuranceIndicator.md

This look like that in this case:

- RP (testrp in this case) default to AAI_LEVEL=MEDIUM as no level is otherwise set
- Fallback mapping is:
LOW: []
MEDIUM: [2FA, HIGH_ASSURANCE_IDP] #<= its fixed now for Google accounts
HIGH: []
MAXIMUM: []

Case 1 (LDAP):
- User logins in with LDAP and has AAI=2FA (as all LDAP requires 2FA)
- Access control verifies 2FA is in MEDIUM set above (which it is)
- Access is granted

Case 2 (Passwordless):
- User logins with a passwordless account and has AAI="" (empty) (no 2FA)
- Access control verifies <nothing> is in MEDIUM set above - this will fail
- Access is denied and an error is triggered
- Currently the error code is not supported, so "something went wrong" is shown

Case 3 (Google):
- User logins with a Google account has AAI=HIGH_ASSURANCE_IDP
- Access control verifies HIGH_ASSURANCE_IDP is in MEDIUM set above - it is
- Access is granted

Case 4 (GitHub/FxA w/ 2FA):
- User logins with an FxA account, which happen to have 2FA enabled, and thus has AAI=2FA
- Access control verifies 2FA is in MEDIUM set above (which it is)
- Access is granted

Case 5 (GitHub/FxA without 2FA):
- User logins with an FxA account and the user has no 2FA -thus has AAI="" (empty)
- Access control verifies 2FA is in MEDIUM set above (which it is)
- Access control verifies <nothing> is in MEDIUM set above - this will fail
- Access is denied and an error is triggered
- Currently the error code is not supported, so "something went wrong" is shown

Hope this helps understand how the feature works

**Comment by gdestuynder** [comment]
@rleitan what is your currently list of tests regarding passwordless logins? (ie which testrp sites are currently tested with it)

With our new code, it now must be verified to fail for some testrp sites, and to succeed for others.
Currently / with the new one above its:

- https://aai-low-social-ldap-pwless.testrp.security.allizom.org/ passwordless must work (this will work when https://github.com/mozilla-iam/sso-dashboard-configuration/pull/181 is merged)
- https://social-ldap-pwless.testrp.security.allizom.org/ and every other - passwordless must fail

I can change that setup of course, as long as we have at least one fail and one succeeds

**Comment by rleitan** [comment]
The bug was discovered during testing the new mozillians [staging](https://web-mozillians.stage.infra.iam.mozilla.com/en-US/) on Kubernetes infrastructure.
We will also take a look at the login in the other testrp sites.

Thanks for clarifications.

**Comment by viorelaioia** [comment]
@gdestuynder , one more thing. I tried to login to https://aai-low-social-ldap-pwless.testrp.security.allizom.org/, but I'm getting the error below. Probably because the [authorized groups](https://github.com/mozilla-iam/sso-dashboard-configuration/blob/259b9a682d563aca272ec71a975bfd11be02e5c6/apps.yml#L818) is set to empty list for this RP?
![cannot login](https://user-images.githubusercontent.com/5293100/46542310-ca6cae00-c8c6-11e8-82af-0b5f28945296.png)

**Comment by gdestuynder** [comment]
My bad I forgot the default group https://github.com/mozilla-iam/sso-dashboard-configuration/pull/184

**Comment by gdestuynder** [comment]
works/tested

**Comment by viorelaioia** [comment]
@gdestuynder , passwordless login is still not working in mozillians staging or sso staging. 
The generic error page ("Oye, something went wrong.") is returned when clicking the login link.

**Comment by gdestuynder** [comment]
Note, https://github.com/mozilla-iam/sso-dashboard/pull/344#issuecomment-428673651 fixes the generic error page until nlx implements this

**Comment by gdestuynder** [comment]
fixed typo in AAI lookup, (lower vs upper case) https://github.com/mozilla-iam/auth0-deploy/pull/225

**Comment by gdestuynder** [comment]
@viorelaioia closing for now please reopen if it doesnt work for you
