### ISSUE TITLE
The user should be informed that he needs to login via the most secured account 

### ISSUE THREAD

**Issue by rleitan** [mozilla-iam/auth0-deploy#238]
[Prerequisites]:
use LDAP and Github accounts with the same email address

[Steps to reproduce]:
1.Open a new Firefox profile
2.Open https://aai-low-social-ldap-pwless.testrp.security.allizom.org/ 
3.Log in using Github

[Expected result]:
The user should be informed that he needs to login via the most secured account for that email (e.g. LDAP)

[Actual results]:
Oye, something went wrong error message is displayed

"code": "staffmustuseldap",
  "redirect_uri": "https://aai-low-social-ldap-pwless.testrp.security.allizom.org/redirect_uri",
  "client": "aai-low-social-ldap-pwless.testrp.security.allizom.org",
  "connection": "github",
  "preferred_connection_name": "",
  "iat": 1544620495,
  "exp": 1544624125

**Comment by gdestuynder** [comment]
in this case, the user must use LDAP because it's a staff account. The message is already in staging, but due to a very specific auth0 issue it cannot be shown until the message is present in production (auth0 caches the request with the production URL and we have no way to affect the cache at this time).

I would consider this "working as intended" because of it. You can also swap the error URL to "sso.allizom.org" (instead of sso.mozilla.com) which will display the actual message

hopefully that's ok for me to close the bug
