### ISSUE TITLE
Enable a Passwordless-only Hosted Lock

### ISSUE THREAD

**Issue by tristanweir** [mozilla-iam/auth0-deploy#61]
This is a requirement for TaskCluster's implementation

There is a validation check built into the lock that prevents me from enabling *only* passwordless (with nothing else)

https://github.com/auth0/lock/blob/7a2a99d33badabb030603d748d1e6b5eef5a47be/src/engine/classic.js#L62-L71

**Comment by gdestuynder** [comment]
Had a chat with @djmitche - he does not require the pwless-only hosted lock per se as the modal currently works, and would happily move to the ldap+pwless hosted lock whenever we have done the mozillians.org+ldap transition.

If UX/look differences aren't a problem, I would postpone this issue or even wontfix it in order to focus on other items we have to improve. In particular, in this very use case, the UX is *already* split because LDAP would still use Okta while "persona" would use pwless (see login.taskcluster.net for an example of this).

In the mean time I sent a PR to fix the branding of the modal dialog: https://github.com/taskcluster/taskcluster-login/pull/39

**Comment by tristanweir** [comment]
Agree with @gdestuynder and I'll move this off the first Hosted Lock milestone. We will defer until a later date, when maybe Auth0 will provide a solution for us.

**Comment by gene1wood** [comment]
We don't need this anymore as we're now using the new NLX lock
