### ISSUE TITLE
Cannot login using LDAP on Mozillians.org

### ISSUE THREAD

**Issue by MikkCZ** [mozilla-iam/auth0-deploy#75]
After mozillians.org replaced Persona by LDAP and passwordless login options, I have an issue with signind via my LDAP account there. It works on l10n.mozilla.org, passwordreset.mozilla.org and login.mozilla.com, but when using my LDAP on Mozillians.org, I end up with 2-Step Verification error "Access Denied. The username you have entered cannot authenticate with Duo Security. Please contact your system administrator.".

I have already contacted #commtools asking about this. There is know bug for the passwordless auth, but with the LDAP issue I have been directed here.

**Comment by MikkCZ** [comment]
To add, I am not staff, but have the LDAP account for l10n commit access etc.

**Comment by gene1wood** [comment]
@MikkCZ When you say "There is know bug for the passwordless auth" do you mean "There is known bug for the passwordless auth" or "There is no bug for the passwordless auth"?

If you mean "There is known bug for the passwordless auth" can you point me to what bug you're referring to?

**Comment by MikkCZ** [comment]
I have been told on #commtools on IRC, that there is a bug for it, but do not have the link, sorry. There is a workaround (login in Firefox private mode), but that works for passwordless only, not LDAP.

**Comment by gene1wood** [comment]
Ok, I'll ping around in #comtools to find out if anyone knows what bug they were referring to.

And do you consistently experience this bug with passwordless auth that you mention? Can you share some of the details about what you experience.

**Comment by gene1wood** [comment]
@johngian looked through IRC logs and found this as the bug that was mentioned : https://bugzilla.mozilla.org/show_bug.cgi?id=1319822

@MikkCZ as we made a production deploy of the fix mentioned in that bug this morning could you try a passwordless login (aka email login) again and see if it works?

**Comment by MikkCZ** [comment]
The e-mail login works on mozillians.org now, but does not on AirMo and some people complained about it on Mozilla Reps Telegram today too. This is what I see after pasting the code for e-mail login on AirMo:
![snimek obrazovky 2016-11-28 v 20 40 27-fullpage](https://cloud.githubusercontent.com/assets/3941344/20683095/f012a29e-b5aa-11e6-9dac-53bb05623dac.png)

LDAP on mozillians.org and Google and GitHub login on AirMo have the same problem, both in normal and private browsing mode.

**Comment by gene1wood** [comment]
> LDAP on mozillians.org ... have the same problem, both in normal and private browsing mode.

This is expected and we're looking into how to enable duo for everyone in LDAP

> The e-mail login works on mozillians.org now

Which email address are you using that works for mozillians.org passwordless email login?

> ...e-mail login ... does not on AirMo

Are you using the same email address on air.mozilla.org as you are on mozillians.org when you get the Duo error message on air.mozilla.org? If not what email address are you using for passwordless email login on air.mozilla.org?

> ... Google and GitHub login on AirMo have the same problem, both in normal and private browsing mode.

What google account are you using on air.mozilla.org, same as the passwordless email address? What github account are you using?

Though it is expected that you would get the Duo error when attempting to login with LDAP, getting that error with passwordless, github or google is not expected. That's the reason I'm trying to get more detail about those cases to understand what's causing it.

**Comment by MikkCZ** [comment]
I use mstankeATmozillaDOTcz for all mentioned.

**Comment by gene1wood** [comment]
# Passwordless email login on air.mozilla.org

In checking our logs I do see your successful passwordless login to mozillians.org. I also see a single air.mozilla.org passwordless code sent by email but no log of when you type in the code to air.mozilla.org.

Can you confirm that the [screenshot you provided](https://github.com/mozilla-iam/auth0-deploy/issues/75#issuecomment-263373088) was what you got after typing in the 6 digit number into air.mozilla.org?

Would it be possible for you to create an [HAR file](https://auth0.com/docs/tutorials/troubleshooting-with-har-files) of the passwordless email triggering a Duo error and send it to me gpg encrypted? You can find my [GPG public key here](https://keybase.io/gene_wood/)

# Github login on air.mozilla.org

In the logs I'm unable to find your github login attempts. When you go to the [Github email settings](https://github.com/settings/emails) do you see the email address you [mentioned above](https://github.com/mozilla-iam/auth0-deploy/issues/75#issuecomment-263394016) in the `Email` section with a green `Primary` tag next to it indicating it's the primary github email address? If not, what email do you have set as your github primary email?

# Google login on air.mozilla.org

In the logs I'm unable to find your Google login attempts. When you click the Google social login on air.mozilla.org, can you confirm that you're successfully logging in to your Google account with your @mozilla.cz email address? I ask because the Auth0 logs don't show any Google auth attempts with your email address you [mentioned above](https://github.com/mozilla-iam/auth0-deploy/issues/75#issuecomment-263394016). If you're using a different Google account email address, can you share it with me so I can see your login attempt in the logs?

# LDAP login on mozillians.org

You'd mentioned that you logged into mozillians.org with your @mozilla.cz LDAP account and got the Duo error. In searching both the auth0 and duo logs I wasn't able to find any successful or failed LDAP login attempts. Can you confirm that you

1. Browsed to https://mozillians.org/
2. Clicked the `Sign In` button
3. You were taken to the https://auth.mozilla.auth0.com/login page
4. You clicked "Log In With LDAP"
5. You typed in your @mozilla.cz email address [mentioned above](https://github.com/mozilla-iam/auth0-deploy/issues/75#issuecomment-263394016) and your valid LDAP password
6. The Duo error message [above](https://github.com/mozilla-iam/auth0-deploy/issues/75#issuecomment-263373088) was displayed

If so, would it be possible to get an [HAR file](https://auth0.com/docs/tutorials/troubleshooting-with-har-files) of this sequence as well?

**Comment by MikkCZ** [comment]
Yes it was after I pasted the six digit code from the e-mail.

My @mozilla.cz address is Mozilla Community Google account and LDAP account. The LDAP login works without trouble on l10n.mozilla.org and passwordreset.mozilla.org (double checked the password multiple times). My primary on Github is michalATstankeDORcz with @mozilla.cz set as additional.

I couldn't make your key work - gpg was complaining a lot. So not uploading it here, rather sending via e-mail.

**Comment by gene1wood** [comment]
> I couldn't make your key work - gpg was complaining a lot. So not uploading it here, rather sending via e-mail.

Sounds good, I'll look for that email. You can get my key with `gpg --recv-keys 17C0E798512E2ED181E24FF4F0A9E7DCD39E452E` if you want.

**Comment by gene1wood** [comment]
I've been able to reproduce this problem with a test LDAP user that does not have Duo enabled. Being able to reproduce it will make it much easier to figure out the root cause and fix it.

**Comment by gene1wood** [comment]
@MikkCZ This is now fixed in production. You however will continue to be affected by #82 . While we fix #82 you're welcome to just clear your auth.mozilla.auth0.com cookies and you'll be able to login with any auth method, working around bug #82.

Thank you again for reporting this issue as we hadn't tested this case before.

**Comment by MikkCZ** [comment]
Great work! Cleared the cookies and works like a charm now.
